version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_virtualgr
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: virtualgr
    ports:
      - "3308:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  virtualgr:
    build: .
    ports:
      - "8086:8086"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/virtualgr
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  prometheus:
    image: prom/prometheus
    container_name: prometheus_virtualgr
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml


  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
volumes:
  mysql-data:
  grafana_data: